config/routes.rb
Sapphire::Application.routes.draw do

  devise_for :users

  resources :projects do 
    get :search
    get :s, :action => :search_results
    get :upload
    post :upload, :action => :process_upload
    get :add_user
    put :remove_user
    post :associate_user
    post :publish
    resources :collections do
      get :upload
      post :publish
      post :upload, :controller => :projects, :action => :process_upload
      get :export
      get :export_with_files
      get :cv
      get :edit_cv
      resources :items do
        put :restore
      end
      resources :schemas do
        put :restore
      end
    end
  end

  root :to => 'projects#index'

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :get_project
  before_filter :get_filters

  def index
    @collections = @project.data_collections
  end

  def show
    @collection = @project.data_collections.get(params[:id])
    @item = @collection.items.new(params[:item])
    @filter_item = @collection.items.new
    if params[:options] == "AND" || params[:options].nil? || @filters.empty?
      @items =  @collection.items.all(@filters)
    else
      @items = @collection.items(:id=>nil)
      @filters.each do |k,v|
        unless v.nil?
          @items = @items + @collection.items.all(k => v)
        end
      end
    end
    
    @items_raw = @items
  end

  def edit
    @collection = @project.data_collections.get(params[:id])
  end

  def edit_cv
    @collection = @project.data_collections.get(params[:collection_id])
  end
  
  def update
    @collection = @project.data_collections.get(params[:id])
    if @collection.update(params[:collection])
      flash[:notice] = "Collection updated!"
    else
      flash[:error] = "Collection failed to update! Errors: " + @collection.errors.full_messages.join(', ')
    end
    redirect_to project_collection_path(@project, @collection)
  end
  
  def new
    @collection = @project.data_collections.new
  end
  
  def create
    @collection = @project.data_collections.new(params[:collection])
    @collection.type = Yogo::Collection::Data
    if @collection.save
      flash[:notice] = "Collection \"#{@collection.name}\" created!"
      if @collection.category == "Controlled Vocabulary"
        #create term and description columns
        @collection.schema.create(:name=>"Term", :type=>Yogo::Collection::Property::String, :position=>0)
        @collection.schema.create(:name=>"Description", :type=>Yogo::Collection::Property::Text, :position=>1)
      end  
      redirect_to project_collection_path(@project, @collection)
    else
      flash[:error] = "Collection failed to save! Errors: " + @collection.errors.full_messages.join(', ')
      redirect_to :back
    end
  end
  
  def destroy
    @collection = @project.data_collections.get(params[:id])
    @collection.deleted_at = Time.now
    if @collection.save
     flash[:notice] = "Collection was Deleted."
      redirect_to project_path(@project)
    else
      flash[:error] = "Collection failed to Delete! Errors: " + @collection.errors.full_messages.join(', ')
      redirect_to project_path(@project)
    end
  end
  
  #use this API to publish or unpublish
  #this essentially toggles the private field
  def publish
    unless current_user.memberships(:project_id => params[:project_id]).empty?
      @collection = @project.data_collections.get(params[:collection_id])
      @collection.private = @collection.private == true ? false : true
      if @collection.save
        flash[:notice] = "Collection successfully changed publicaction status."
        redirect_to project_collection_path(@project,@collection)
      else
        flash[:error] = "Collection failed to change publication status! Errors: " + @collection.errors.full_messages.join(', ')
        render :index
      end
    else
      flash[:error] = "You don't have permission to change publication status!"
      render :index
    end
  end
  
  def export
    @collection = @project.data_collections.get(params[:collection_id])
    filename ="#{@collection.name}.csv"
    csv_string = create_collection_csv_string(@collection, @filters)      
    send_data(csv_string,
      :type => 'text/csv; charset=utf-8; header=present',
      :filename => filename)
  end
  
  def export_with_files
    require 'zip/zip'
    @collection = @project.data_collections.get(params[:collection_id])
    filename ="#{@collection.name}-#{Time.now.to_i}.zip"
    filename_array = []
    file_uid_array = []
    Zip::ZipFile.open("tmp/downloads/"+filename, Zip::ZipFile::CREATE) do |z|
      
      @collection.items.all.each do |item|
        
        begin
          @collection.schema.all(:is_file=>true).each do |field|

           unless item[field.name].nil?
             if   filename_array.count(@file_collection.items.get(JSON.parse(item[field.name])['item']['id']).original_filename) > 0
               if file_uid_array.count(@file_collection.items.get(JSON.parse(item[field.name])['item']['id']).file.to_s) == 0
                 base_filename = @file_collection.items.get(JSON.parse(item[field.name])['item']['id']).original_filename
                 new_filename = base_filename + "2"
                 count = 2
                 while filename_array.count(new_filename) > 0 do
                    count = count + 1
                    new_filename = base_filename + count.to_s
                 end
                 z.add(new_filename, "public/"+@file_collection.items.get(JSON.parse(item[field.name])['item']['id']).file.to_s)
                 filename_array << new_filename
                 file_uid_array << @file_collection.items.get(JSON.parse(item[field.name])['item']['id']).file.to_s
               end
             else 
               z.add(@file_collection.items.get(JSON.parse(item[field.name])['item']['id']).original_filename, "public/"+@file_collection.items.get(JSON.parse(item[field.name])['item']['id']).file.to_s)
               filename_array << @file_collection.items.get(JSON.parse(item[field.name])['item']['id']).original_filename
               file_uid_array << @file_collection.items.get(JSON.parse(item[field.name])['item']['id']).file.to_s
             end
           end
          end
        rescue Exception => e 
          puts e.message  
          #puts e.backtrace.inspect
          #z.add(item.original_filename + "_2", "public/"+item.file.to_s)
        end
      end
      csv_string = create_collection_csv_string(@collection,@filters, true)
      new_file = "tmp/downloads/#{@collection.name}_"+Time.now.to_s+".csv"
      File.open(new_file, "wb"){ |f| f.write(csv_string)}
      z.add("#{@collection.name}_"+Time.now.to_s+".csv",new_file)
      z.close()
    end
    send_file("tmp/downloads/"+filename, :type => 'application/zip')
  end
   
  def upload
    render 'projects/upload'
  end
  
  # TODO: Is this necessary?
  def cv
    @collection = @project.data_collections.get(params[:collection_id])
    @schema_cv_hash={}
    @collection.schema.each do |s|
      link_hash={}
      if s.controlled_vocabulary_id
        @schema_cv_hash[s.id] = Yogo::Collection::Property.get(s.controlled_vocabulary_id).data_collection
        s.data_collection.items.each do |i|
          link_hash = link_hash.merge({i[s.name] => @schema_cv_hash[s.id].items.first("field_#{s.controlled_vocabulary_id.to_s.gsub('-','_')}".to_sym=>i[s.name])})
        end
        @schema_cv_hash[s.name]=link_hash
      end
    end
  end


  private
  def get_project
    if !Yogo::Collection::Data.get(params[:id]).nil? 
      if Yogo::Collection::Data.get(params[:id]).private
        #project is private so you need to be a member
        verify_membership
      end
    elsif !Yogo::Collection::Data.get(params[:collection_id]).nil?
      if Yogo::Collection::Data.get(params[:collection_id]).private 
        #project is private so you need to be a member
        verify_membership
      end
    end
    #if we are here the project is public so proceed
    @project = Yogo::Project.get(params[:project_id])
    @file_collection = @project.data_collections.first(:category=>"Files")
  end
  
  def verify_membership
    if Yogo::Project.get(params[:project_id]).private
      if current_user.memberships(:project_id => params[:project_id]).empty?
        flash[:error] = "You don't have access to that project!"
        redirect_to projects_path()
        return
      end
    end
    #you are member or project is public -proceed
  end
  
  def create_collection_csv_string(collection, conditions, file=false)
    name_array = []#collection.schema.map(&:name)
    collection.schema.each do |schema|
      if schema.associated_schema 
        schema.associated_schema.data_collection.schema.each do |s| 
          name_array << schema.name+"_"+s.name
        end
        #name_array << schema.name+"_File"
      else
        name_array << schema.name
      end
    end
    #name_array << "File"
    field_array = collection.schema.map(&:to_s)
    
    # if file == true
    #   name_array << "File"
    #   field_array << :original_filename
    # end
    csv_string = CSV.generate do |csv|
      csv << name_array
      DataMapper.raw_select(collection.items.all(:fields=>collection.schema.map{|s| s.field_name}).all(conditions)).each do |item|
        row_array = []
        collection.schema.each do |s|  
          if s.associated_schema
            unless item[s.field_name].nil?
              json_string = JSON.parse(item[s.field_name])
              assoc_item = s.associated_schema.data_collection.items.get(json_string['item']['id'])
              s.associated_schema.collection.data_collection.schema.each do |assoc|
                if assoc.associated_schema
                  unless assoc_item[assoc.name].nil?
                    row_array << JSON.parse(assoc_item[assoc.name])['item']['display']
                  else
                    row_array <<""
                  end
                else
                  row_array << (assoc.name == "File" ? assoc_item.original_filename : assoc_item[assoc.name].to_s)
                end
              end
              #row_array << item.original_filename
            else
              s.associated_schema.data_collection.schema.each do |s|
                row_array << ""
              end
              row_array << ""
            end
          elsif s.is_file && !item[s.field_name].nil?
            row_array << JSON.parse(item[s.field_name])['item']['display']
          else
            row_array << (s.name == "File" ? item.original_filename : item[s.field_name].to_s)
          end
        end
        #row_array << item.original_filename
        csv << row_array
      end
    end
    csv_string
  end

app/helpers/collections_helper.rb
module CollectionsHelper
  
  def collection_category_options
    [["None",""],["Controlled Vocabulary", "Controlled Vocabulary"]]
  end
  
end

app/views/collections/_filter.haml
#edit-filters.modal.hide.fade
  .modal-header
    %button.close(data-dismiss="modal") x
    %h3 Filter Data
  = form_for("filters", filter_item, :url => project_collection_path(project, collection),  
            :html => {:class => 'modal-form',:method=>:get}) do |f|  
    - collection.schema.each do |field|
      %label=field.name
      -if field.controlled_vocabulary
        = f.select(field.to_s, field_value_options(field.controlled_vocabulary),  :include_blank => true,:selected=> params[:filters].nil? ? "" : params[:filters][field.to_s].nil? ? "": params[:filters][field.to_s])
      -elsif field.associated_schema 
        = f.select(field.to_s, associated_field_display_options(field.associated_schema),  :include_blank => true,:selected=> params[:filters].nil? ? "" :params[:filters][field.to_s].nil? ? "": params[:filters][field.to_s])
      -elsif field.is_file == true
        = f.select(field.to_s, associated_file_options(@file_collection),  :include_blank => true,:selected=> params[:filters].nil? ? "" :params[:filters][field.to_s].nil? ? "": params[:filters][field.to_s])
      -else
        = f.text_field(field.to_s, :value=> params[:filters].nil? ? "" :params[:filters][field.to_s].nil? ? "": params[:filters].nil? ? "" : params[:filters][field.to_s]) 
    %p
      And
      =radio_button_tag("options", "AND")
      OR
      =radio_button_tag("options", "OR")
      -unless params["options"].nil?
        :javascript
          $('#options_#{params[:options]}').attr("checked", true)
      -else
        :javascript
          $('#options_AND').attr("checked", true)
    .modal-footer
      %button.btn.btn-primary Filter
      %a.btn.btn-mini(data-dismiss="modal") Close

app/views/collections/_form.haml
%label Name
= f.text_field(:name, :placeholder => 'Collection Name')
%label Description
= f.text_area(:description, :rows => 5, :placeholder => 'Collection Description')
%label Category
= f.select(:category, collection_category_options)
%label.checkbox
  =f.check_box(:private) 
  Collection is Private

app/views/collections/_list.haml
%table.table
  %thead
    %tr
      %th Collection
      %th Description
      %th Columns
      %th Data Items
      %th &nbsp;
  %tbody
    - collections.each do |c|
      %tr
        %td
          %h4= link_to(c.name, project_collection_path(c.project_id,c))
          - if c.public?
            %span.label.label-info Public
          - else
            %span.label.label-default Private
        %td= c.description.blank? ? "No Description." : c.description
        %td= c.schema.map(&:name)
        %td= c.items.count
        %td= link_to("delete", project_collection_path(c.project_id,c), :class => 'btn btn-warning btn-mini',
                      :method=>:delete, "data-confirm"=>"Are you sure you wish to delete this Collection?")

app/views/collections/cv.haml
%h1 #{@project.name} > Controlled Vocabulary:#{@collection.name}

.block
  .secondary-navigation.button-navigation
    .wat-cf
      -unless current_user.memberships.all(:project_id=>@project.id).empty? || @project.private
        = nav_button("Back to Project", "web-app-theme/icons/arrow_undo.png", project_path(@project))
      -unless current_user.memberships.all(:project_id=>@project.id).empty?
        = nav_button("Edit Controled Vocabulary Collection", "web-app-theme/icons/application_edit.png", project_collection_edit_cv_path(@project,@collection))
        -if @project.private #if the project is not published show these
          -if @collection.private
            = nav_button("Publish Controlled Vocabulary",  "web-app-theme/icons/world_add.png", project_collection_publish_path(@project,@collection), "post")
          -else
            = nav_button("Unpublish Controlled Vocabulary",  "web-app-theme/icons/world_delete.png", project_collection_publish_path(@project,@collection), "post")
  -unless current_user.memberships.all(:project_id=>@project.id).empty?
    .content
      .inner
        %h3 
          Add New Schema
          %a{:id=>"schema_add", :href=>"javascript:toggle('add_schema','schema_add');"}
            %img{:src=>'/images/web-app-theme/icons/add.png', :height=>'16px'}
        %div{:id=>"add_schema", :style=>'display:none;'}
          = form_for("schema", :url => project_collection_schemas_path(@project, @collection), :html => {:class => 'form'}) do |f|
            = render :partial => 'schemas/form', :locals => {:f => f, :collection=>@collection}
            .group.navform.wat-cf
              = f.submit("Save", :submit_image => image_tag("web-app-theme/icons/tick.png", :alt => "Save"))
.block
  .content
    .inner
      %h3 
        Current Schema
        %a{:id=>"displayText", :href=>"javascript:toggle('current_schema','displayText');"}
          %img{:src=>'/images/web-app-theme/icons/add.png', :height=>'16px'}
      %div{:id=>"current_schema", :style=>'display:none;'}
        %ul.list.schema-list
          - @collection.schema.each do |s|
            %li 
              .item 
                -unless current_user.memberships.all(:project_id=>@project.id).empty?
                  =link_to(image_tag("web-app-theme/icons/table_edit.png", :border=>"0", :height=>"16px"), edit_project_collection_schema_path(@project,@collection,s)) 
                #{s.name} (#{s.type.to_s.split('::').last})
                -unless current_user.memberships.all(:project_id=>@project.id).empty?
                  =link_to("delete", project_collection_schema_path(@project,@collection,s), :method=>:delete, "data-confirm"=>"Are you sure you wish to delete this Schema Column?")
-unless current_user.memberships.all(:project_id=>@project.id).empty?
  .block
    .content
      .inner  
        %h3 
          Add Controlled Vocabulary Item    
          %a{:id=>"cv", :href=>"javascript:toggle('add_item','cv');"}
            %img{:src=>'/images/web-app-theme/icons/add.png', :height=>'16px'}
        %div{:id=>"add_item", :style=>'display:none;'}    
          =form_for("item", :url => project_collection_items_path, :html => {"multipart" => true, "data-ajax"=> false, :class => 'form'}) do |f| 
            = render :partial => 'items/form', :locals => {:f => f, :collection => @collection}
            .group.navform.wat-cf
              = f.submit("Save", :submit_image => image_tag("web-app-theme/icons/tick.png", :alt => "Save"), :cancel_link => link_to("Cancel", projects_path, :class => "text_button_padding link_button"))
.block
  .secondary-navigation.button-navigation
    .wat-cf
      -if @collection.schema.count > 0
        = nav_button("Download All Items", "web-app-theme/icons/arrow_undo.png", project_collection_export_path(@project,@collection))
        = nav_button("Download All Items With Files", "web-app-theme/icons/package_go.png", project_collection_export_with_files_path(@project,@collection))
        -unless current_user.memberships.all(:project_id=>@project.id).empty?
          = nav_button("Upload Data", "web-app-theme/icons/application_get.png", project_upload_path(@project, :collection_id=>@collection.id))
  .content
    .inner
      %h3 Data
      -unless current_user.memberships.all(:project_id=>@project.id).empty?
        = render :partial => 'items/table', :locals => {:items => @collection.items(:order => :created_at.desc), :collection => @collection, :project=>@project}
      -else
        = render :partial => 'items/public_table', :locals => {:items => @collection.items(:order => :created_at.desc), :collection => @collection, :project=>@project}
      

:javascript
  function toggle(div_id, image_id) {
  	var ele = document.getElementById(div_id);
  	var text = document.getElementById(image_id);
  	if(ele.style.display == "block") {
      		ele.style.display = "none";
  		text.innerHTML = "<img src='/images/web-app-theme/icons/add.png' height='16px'></img>";
    	}
  	else {
  		ele.style.display = "block";
  		text.innerHTML = "<img src='/images/web-app-theme/icons/delete.png' height='16px'></img>";
  	}
  } 
  
-content_for :sidebar do
  .sidebar-block
    %h2 Filter Data:
    = form_for("filter", :url => project_collection_filter_path(@project,@collection),  :html => {:class => 'form',:method=>:get}) do |f|  
      = render :partial => 'filter', :locals => {:f => f, :collection => @collection, :filters => nil}
      .group.navform.wat-cf
        = f.submit("Filter", :submit_image => image_tag("web-app-theme/icons/tick.png", :alt => "Filter"))

app/views/collections/edit.haml
.content-box
  .modal-header
    %h3 Edit #{@collection.name} Settings
    %p.muted Collection ID: #{@collection.id}
  = form_for("collection",@collection, :url => project_collection_path(@project,@collection), 
            :html => {:method=>"put", :class => 'form-box', :ajax=>false}) do |f|
    .modal-body
      = render :partial => 'collections/form', :locals => {:f => f}
    .modal-footer
      %button.btn.btn-primary Save Changes
      %a.btn(data-dismiss="modal") Close

app/views/collections/edit_cv.haml
%h1 #{@project.name} > Edit Controlled Vocabulary Collection

.block
  .secondary-navigation.button-navigation
    .wat-cf
      = nav_button("Back to Controlled Vocabulary", "web-app-theme/icons/arrow_undo.png", project_collection_cv_path(@project, @collection))
  .content
    .inner
      = form_for("collection",@collection, :url => project_collection_path(@project,@collection), :html => {:class => 'form', :method=> :put}) do |f|
        = render :partial => 'form', :locals => {:f => f}
        =hidden_field_tag(:redirect_path, project_collection_cv_path(@project, @collection))
        .group.navform.wat-cf
          = f.submit("Save", :submit_image => image_tag("web-app-theme/icons/tick.png", :alt => "Save"), :cancel_link => link_to("Cancel", :back, :class => "text_button_padding link_button"))

app/views/collections/index.haml
%h1 Project: #{@project.name}

.block
  .secondary-navigation.button-navigation
    .wat-cf
      = nav_button("Back to Projects", "web-app-theme/icons/arrow_undo.png", projects_path)
      = nav_button("Create a Data Collection", "web-app-theme/icons/add.png", new_project_collection_path(@project))
  .content
    .inner
    
      %ul.list.collection-list
        - @project.data_collections.each do |c|
          %li
            .counts
              .data_items_count Data Items: #{c.items.count}
            .left= image_tag("Yogo-tiny-trans.png")
            %dl
              %dt
                %h4.item 
                  %a{:href => project_collection_path(@project,c)}= c.name
              %dd
                Schema: #{c.schema.map(&:name)}
                %br
                #{c.description.blank? ? "No Description." : c.description}

app/views/collections/new.haml
.content-box
  .modal-header
    %h3 Add New #{@project.name} Collection
  = form_for("collection", :url => project_collections_path(@project), :html => {:class => 'form'}) do |f|
    .modal-body
      = render :partial => 'collections/form', :locals => {:f => f}
    .modal-footer
      %button.btn.btn-primary Save Changes
      %a.btn(data-dismiss="modal") Close

app/views/collections/show.haml
.content-box
  -if (current_user.member_of?(@project) && @collection.schema.count > 0) || @collection.category != "Files"
    = render(:partial => 'collections/filter', 
            :locals => {:filter_item => @filter_item, :collection => @collection, 
                        :project => @project, :filters => @filters})
    = render(:partial => 'items/inline_form', :locals => {:items =>@items, :collection => @collection, :project=>@project})

.content-box
  - if @collection.schema.count > 0 || @collection.category == "Files"
    .header
      %strong Data Grid
    - unless @filters.empty?
      Filtered By: #{@filters.map{|k,v| @collection.schema.by_field_name(k.target.to_s).name + " : #{v}"}.join(' ' + params[:options] + ' ')}
      %a.btn-small(href='#{project_collection_path(@project, @collection)}') Clear Filters
    -if current_user.member_of?(@project)
      -if @collection.category == "Files"
        = render  :partial => 'items/table', 
                  :locals => {:items =>@items, :collection => @collection, :project=>@project}
      -else
        = render  :partial => 'items/grid_new', 
                  :locals => {:items_raw =>@items, :collection => @collection, :project=>@project}
    -else
      = render  :partial => 'items/public_table', 
                :locals => {:items => @items, :collection => @collection, :project=>@project}
  - else
    .row
      .span5
      %a.span2.btn.btn-primary.schema-new(href='#collection_schema_form' data-toggle='modal') 
        Empty Data Collection 
        %br/
        Add a Column!
      .span5