config/routes.rb
Sapphire::Application.routes.draw do

  devise_for :users

  resources :projects do 
    get :search
    get :s, :action => :search_results
    get :upload
    post :upload, :action => :process_upload
    get :add_user
    put :remove_user
    post :associate_user
    post :publish
    resources :collections do
      get :upload
      post :publish
      post :upload, :controller => :projects, :action => :process_upload
      get :export
      get :export_with_files
      get :cv
      get :edit_cv
      resources :items do
        put :restore
      end
      resources :schemas do
        put :restore
      end
    end
  end

  root :to => 'projects#index'

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :verify_project, :only =>[:show, :edit, :update, :upload, :process_upload, :search, :search_results]
    
    def index
        @projects = current_user.memberships.projects
        @public_projects = Yogo::Project.all(:private => false) - current_user.memberships.projects
    end

    def show
      @project = Yogo::Project.get(params[:id])
      @cv_collections = @project.data_collections(:category => "Controlled Vocabulary")
      @collections = @project.data_collections(:category =>"")
      @file_collection = @project.data_collections(:category =>"Files")
    end

    def edit
      @project = Yogo::Project.get(params[:id])
    end

    def update
      @project = Yogo::Project.get(params[:id])
      if @project.update(params[:yogo_project])
        flash[:notice] = "Project updated!"
      else
        flash[:error] = "Project failed to save! Errors: " + @project.errors.full_messages.join(', ')

      end
      redirect_to :back
    end
    
    def new
    end
    
    def create
      @project = Yogo::Project.new(params[:yogo_project])
      if @project.save
        current_user.memberships.create(:project_id => @project.id)
        @collection = @project.data_collections.new(:name => "Files", :category=>"Files")
        @collection.type = Yogo::Collection::Asset
        @collection.save
        flash[:notice] = 'New Project created!'
        redirect_to project_path(@project)
      else
        flash[:error] = "Project failed to save! Errors: " + @project.errors.full_messages.join(', ')
        redirect_to :back
      end
    end
    
    def destroy
      #@project = Yogo::Project.get(params[:id])
      #dtime = Time.now
      #@project.data_collections.each do |c|
      #  c.deleted_at = dtime
      #  c.save
      #end
      #@project.deleted_at = dtime
      #if @project.save
      # flash[:notice] = "Project was Deleted."
      #  redirect_to projects_path()
      #else
      #  flash[:error] = "Project failed to Delete" + @project.errors.inspect
        flash[:error] = "Project deletion is currently disabled.  We apoligize for the inconvience and will address this soon."
        redirect_to projects_path()
      #end
    end
    
    def upload
     @project = Yogo::Project.get(params[:project_id])
    end
    
    #use this API to publish or unpublish
    #this essentially toggles the private field
    def publish
      verify_membership
      @project = Yogo::Project.get(params[:project_id])
      @project.private = @project.private == true ? false : true
      if @project.save
        flash[:notice] = "Project successfully changed publicaction status."
        redirect_to project_path(@project)
      else
        flash[:error] = "Project failed to change publication status!"
        render :index
      end
    end
    
    def process_upload
      @project = Yogo::Project.get(params[:project_id])
      @new_file = "temp_data/"+Time.now.to_i.to_s + params[:upload][:file].original_filename 
      File.open(@new_file, "wb"){ |f| f.write(params[:upload][:file].read)}
      # if new data collection
      if params[:upload][:collection].empty?
         #check if file is a zip file
         if @new_file.include?(".zip")
           @data_collection=@project.process_zip_file_to_collection(@new_file,params[:upload][:file].original_filename)
         else
           # create/update data_collection schema
           @data_collection= @project.collection_from_file(params[:upload][:file].original_filename, @new_file)
           # insert items into data_collection
           insert_nonfile_item_into_collection(@new_file, @data_collection)
         end
      else# if existing data collectin
        #TODO update schema?
        #fetch schema
        if @new_file.include?(".zip")
           @data_collection=@project.process_zip_file_to_collection(@new_file,params[:upload][:file].original_filename, @data_collection)
        else
          @data_collection =  @project.data_collections.get(params[:upload][:collection])
          #if there are new field update the collection
          @data_collection= @project.collection_from_file(params[:upload][:file].original_filename, @new_file, @data_collection)
          # insert items into data_collection
          insert_nonfile_item_into_collection(@new_file, @data_collection)
        end
      end
      
      # redirect to data collection index
      redirect_to project_collection_path(@project.id, @data_collection.id)
    end
    
    def search
      @project = Yogo::Project.get(params[:project_id])
    end
    
    def search_results
      @project = Yogo::Project.get(params[:project_id])
      @data_collections = @project.data_collections
      @search_results = @project.full_text_search(params[:search][:terms].downcase)
      @schema_cv_hash={}
      collections = @project.data_collections.all(:id=>@search_results.keys)
      collections.each do |coll|
        coll.schema.each do |s|
          link_hash={}
          if s.controlled_vocabulary_id
            @schema_cv_hash[s.id] = Yogo::Collection::Property.get(s.controlled_vocabulary_id).data_collection
            s.data_collection.items.each do |i|
              link_hash = link_hash.merge({i[s.name] => @schema_cv_hash[s.id].items.first("field_#{s.controlled_vocabulary_id.to_s.gsub('-','_')}".to_sym=>i[s.name])})
            end
            @schema_cv_hash[s.name]=link_hash
          end
        end
      end
    end
    
    def add_user
      @project = Yogo::Project.get(params[:project_id])
    end
    
    #remove a user from a project
    def remove_user
      @project = Yogo::Project.get(params[:project_id])
      @user = User.get(params[:user_id].to_i)
      if @user.memberships.first(:project_id=> @project.id).destroy
        flash[:notice] = "#{@user.first_name} #{@user.last_name} has been removed from this project."
      else
        flash[:error] = "Failed to add user! Errors: " + @user.errors.full_messages.join(', ')
      end
      redirect_to :back
    end
    
    def associate_user
      @project = Yogo::Project.get(params[:project_id])
      @user = User.get(params[:add_user][:user_id].to_i) if params[:add_user]
      if @user && @user.memberships.first_or_create(:project_id=> @project.id)
        flash[:notice] = "#{@user.first_name} #{@user.last_name} has been add to this project."
      else
        flash[:error] = "Failed to add user! Errors: " + @user.errors.full_messages.join(', ')
      end
      redirect_to :back
    end
    
    private
    
    def insert_nonfile_item_into_collection(file, collection)
      # insert items into data_collection
      item = collection.items.create()
      row_values = []
      version_values=[]
      schema_cols = []
      schema_fields= []
      collection.schema.each do |s| 
        schema_cols << s.name
        schema_fields << s.field_name
      end
      time_now = Time.now
      CSV.read(file, :headers => true).each do |row|
        item_id = UUIDTools::UUID.timestamp_create
        row_values << "('#{item_id}','CREATED','#{time_now}','#{time_now}','#{current_user.id}',#{schema_cols.map{|col| row[col].blank? ? "\'null\'" : "\'#{row[col]}\'"}.join(',')})"
        ver_id =UUIDTools::UUID.timestamp_create
        version_values <<"('#{ver_id}','CREATED','#{time_now}','#{time_now}','#{current_user.id}',#{schema_cols.map{|col| row[col].blank? ? "\'null\'" : "\'#{row[col]}\'"}.join(',')}, '#{time_now}','#{item_id}')"
      end
      sql = "INSERT INTO \"#{collection.id.to_s.gsub("-","_")+"s"}\" (\"id\",\"updated_comment\",\"created_at\",\"updated_at\",\"updated_by\",#{schema_fields.map{|col| "\"#{col}\""}.join(',')}) VALUES "
      sql << row_values.join(',')
      repository.adapter.execute(sql)
      
      sql = "INSERT INTO \"#{collection.id.to_s.gsub("-","_")+"s"}\" (\"id\",\"updated_comment\",\"created_at\",\"updated_at\",\"updated_by\",#{schema_fields.map{|col| "\"#{col}\""}.join(',')},\"deleted_at\",\"original_uid\") VALUES "
      sql << version_values.join(',')
      repository.adapter.execute(sql)
      item.destroy
    end
    
    def verify_project
      if !Yogo::Project.get(params[:id]).nil? 
        if Yogo::Project.get(params[:id]).private
          #project is private so you need to be a member
          verify_membership
        end
      elsif !Yogo::Project.get(params[:project_id]).nil?
        if Yogo::Project.get(params[:project_id]).private 
          #project is private so you need to be a member
          verify_membership
        end
      end
      #if we are here the project is public so proceed
    end
    
    def verify_membership
      if current_user.memberships(:project_id => params[:id]).empty? && current_user.memberships(:project_id => params[:project_id]).empty?
        #you aren't a member so go back
        flash[:error] = "You don't have access to that Project!"
        redirect_to projects_path()
      end
      #you are member proceed
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def users_for_select(project)
    users = User.all - project.memberships.users
    users.map{|u| ["#{u.last_name}, #{u.first_name}",u.id] }
  end

end

app/views/projects/_form.haml
%label Project Name
= f.text_field(:name, :placeholder => 'Project Name')
%label Project Description
= f.text_area(:description, :rows => 5, :placeholder => 'Project Description')
%label.checkbox
  =f.check_box(:private) 
  Project is Private

app/views/projects/_list.haml
%table.table
  %thead
    %tr
      %th Project Name
      %th Stats
      %th Description
      %th &nbsp;
  %tbody
    - projects.each do |p|
      %tr
        %td
          %h4= link_to p.name, project_path(p)
          - if p.public?
            %span.label.label-info Public
          - else
            %span.label.label-default Private
        %td
          .collection_count Data Collections: #{p.data_collections.count}
          .data_items_count Data Items: #{p.record_count}
        %td
          %p= p.description.blank? ? "No Description." : p.description
          %p= "Members: " + p.members.map{|m| m.user.first_name }.join(', ')
        %td 
          - if current_user.member_of?(p)
            = link_to("delete", project_path(p), 
              :class => 'btn btn-warning btn-mini',:method=>:delete, 
              "data-confirm"=>"Are you sure you wish to delete this Project?")

app/views/projects/_project_users.haml
= form_for("add_user", :url => project_associate_user_path(@project), :html => {:class => 'form-inline'}) do |f|
  .modal-body
    = f.select(:user_id,options_for_select(users_for_select(@project)))
    %button.btn.btn-primary Add User

%table.table.table-striped
  %thead
    %tr
      %th Last Name
      %th First Name
      %th Email
      %th &nbsp;
  %tbody
    -@project.members.users(:order => [:last_name]).each do |user|
      %tr
        %td= user.last_name
        %td= user.first_name
        %td= user.email
        - if @project.members.count == 1
          %td
            %a.btn.btn-mini(href='#' disabled) remove
        - else
          %td= link_to("remove", project_remove_user_path(@project, :user_id=>user.id), 
                      :class => 'btn btn-warning btn-mini', :method => :put, 
                      "data-confirm"=>"Are you sure you wish to remove this user from the project?")

app/views/projects/_upload_form.haml
= form_for('upload', :url => project_upload_path(@project), :html => {"multipart" => true, "data-ajax"=> false, :class => 'modal-form'}) do |f|
  .modal-body
    %label Upload Into:
    - if @collection
      %input(type='text' placeholder='#{@collection.name}' disabled)
      %input(type='hidden' id='upload_collection' name='upload[collection]' value='#{@collection.id}')
    - else
      = select("upload","collection", @project.data_collections.all.collect{|d| [d.name, d.id]}, 
            {:required=>true,:include_blank => 'A New Collection'})
    = f.file_field :file
  .modal-footer
    %button.btn.btn-primary Upload File
    %a.btn.btn-mini(data-dismiss="modal") Close

app/views/projects/add_user.haml
%h1 Add User to #{@project.name}

.block
  .secondary-navigation.button-navigation
    .wat-cf
      = nav_button("Back to Project", "web-app-theme/icons/arrow_undo.png", project_path(@project))
  .content
    .inner
      = render :partial => 'project_users', :locals => {:project => @project,
      :cancel_link => nil}

app/views/projects/edit.haml
.content-box
  .modal-header
    %h3 Edit #{@project.name} Project Settings
    %p.muted Project ID: #{@project.id}
  = form_for(@project, :url => project_path, :html => {:class => 'form-box', :method=> :put}) do |f|
    .modal-body
      = render :partial => 'projects/form', :locals => {:f => f}
    .modal-footer
      %button.btn.btn-primary Save Changes
      %a.btn(data-dismiss="modal") Close

app/views/projects/index.haml
.tabbable
  %ul.nav.nav-pills
    %li.active= link_to("My Projects (#{@projects.count})", "#myproj-tab", 'data-toggle' => 'tab')
    %li= link_to("Public Projects (#{@public_projects.count})", "#pubproj-tab", 'data-toggle' => 'tab')
  .tab-content.content-box
    #myproj-tab.tab-pane.active
      - if @projects.count > 0
        = render(:partial => 'projects/list', :locals => {:projects => @projects})
      - else 
        .span5
        %a.span2.btn.btn-large.btn-primary.project-new(href='#new_project_form' data-toggle='modal') 
          No Projects...
          %br/
          Create a Project!
        .span5
    #pubproj-tab.tab-pane
      = render(:partial => 'projects/list', :locals => {:projects => @public_projects})

app/views/projects/new.haml
.content-box
  .modal-header
    %h3 Create New Project
  = form_for(Yogo::Project.new, :url => projects_path, :html => {:class => 'form-box'}) do |f|
    .modal-body
      = render :partial => 'projects/form', :locals => {:f => f}
    .modal-footer
      %button.btn.btn-primary Save Changes
      %a.btn(data-dismiss="modal") Close

app/views/projects/process_search.haml
%h1 Search Results:
.block

  .content
    .inner
      %h4 #{@search_results.map{|k,v| v.length}.inject(:+)} records match your query.

- @search_results.each do |collection, items|
  -unless items.empty?
    .content
      .block
        .secondary-navigation.button-navigation
          .wat-cf
            = nav_button(collection.name,"web-app-theme/icons/table.png" ,project_collection_path(@project, collection))
        .content
          .inner
            %h3= collection.name
            = render :partial => 'items/table', :locals => {:items => items, :collection => collection}

app/views/projects/process_search.js.erb
$("#search_results").html( '<%= escape_javascript(render(:partial => "show_search_results",
                                      :locals => {
                                        :search_results => @search_results}))%>' )

$('loading_dialog').toggle();

app/views/projects/search.haml
%h1 Search Data in #{@project.name}:
.block
  .secondary-navigation.button-navigation
    .wat-cf
      = nav_button("Back to Project", "web-app-theme/icons/arrow_undo.png", project_path(@project))
  .content
    .inner
      = form_for(:search, :url => project_s_path, :html => {:class => 'form', :method => :get}) do |f|
        .group= f.text_field(:terms, :label => 'Search Terms')
        .group.navform.wat-cf
          = f.submit("Perform Search",:submit_image => image_tag("web-app-theme/icons/search.png", :alt => "Save"), :cancel_link => link_to("Cancel", projects_path, :class => "text_button_padding link_button"))

app/views/projects/search_results.haml
%h2 Search Results:
%h4 #{@search_results.map{|k,v| v.length}.inject(:+)} record(s) match your query.

.search_results.content-box
  -@search_results.keys.each do |coll|
    -if @search_results[coll].length > 0
      -cur_collection=@data_collections.get(coll)
      -unless cur_collection.nil?
        %hr
        .container
          .span11
            %h4= cur_collection.name
            -if current_user.member_of?(@project)       
              = render :partial => '/items/table', :locals => {:items => @search_results[coll], :collection => cur_collection, :project=>@project}
            -else
              = render :partial => '/items/public_table', :locals => {:items => @search_results[coll], :collection => cur_collection, :project=>@project}

app/views/projects/search_results.js.erb
$("#search_results").html( '<%= escape_javascript(render(:partial => "show_search_results",
                                      :locals => {
                                        :search_results => @search_results}))%>' )

$('loading_dialog').toggle();

app/views/projects/show.haml
.tabbable
  %ul.nav.nav-pills
    %li.active= link_to("Data Collections (#{@collections.count})", "#dc-tab", 'data-toggle' => 'tab')
    %li= link_to("Controlled Vocabularies (#{@cv_collections.count})", "#cv-tab", 'data-toggle' => 'tab')
    %li= link_to("Files", "#file-tab", 'data-toggle' => 'tab')
    
  .tab-content.content-box
    #dc-tab.tab-pane.active
      - if @collections.count > 0
        = render(:partial => "collections/list", :locals=>{:collections => @collections})
      - else 
        .span5
        %a.span2.btn.btn-primary.collection-new(href='#new_collection_form' data-toggle='modal') 
          No Data Collections...
          %br/
          Create a Collection!
        .span5
    #cv-tab.tab-pane
      -unless @cv_collections.empty?
        = render(:partial => "collections/list", :locals=>{:collections => @cv_collections})
    #file-tab.tab-pane
      = render(:partial => "collections/list", :locals=>{:collections => @file_collection})