config/routes.rb
Sapphire::Application.routes.draw do

  devise_for :users

  resources :projects do 
    get :search
    get :s, :action => :search_results
    get :upload
    post :upload, :action => :process_upload
    get :add_user
    put :remove_user
    post :associate_user
    post :publish
    resources :collections do
      get :upload
      post :publish
      post :upload, :controller => :projects, :action => :process_upload
      get :export
      get :export_with_files
      get :cv
      get :edit_cv
      resources :items do
        put :restore
      end
      resources :schemas do
        put :restore
      end
    end
  end

  root :to => 'projects#index'

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :get_dependencies
  after_filter :update_project_stats, :only => [:create, :delete]

  def index
    if params[:item]
      @item = @collection.items.new(params[:item])
    else
      @item =@collection.items.new()
    end 
    respond_to do |format|
      format.html {render :index}
      format.json {render :json => @collection.items.page(params[:page], :per_page=>50).to_json}
    end
  end
  
  #expects the delete_at datetime in params[:deleted_at]
  def restore
     @item = @collection.items.get(params[:item_id])
     old_item = @item.versions.first(:deleted_at => params[:deleted_at])
     att = old_item.attributes
     att.delete(:deleted_at)
     att.delete(:original_uid)
     att.delete(:id)
     if @item.update(att)
       flash[:notice] = "Item Restored Successfully!"
       redirect_to project_collection_item_path(@project, @collection, @item)
     else
       flash[:error] = "Item failed to restore!"
       render :show
     end
  end
  
  # TODO: move the nullification of the fields into a before :save
  def update
    @item = @collection.items.get(params[:id])
    @collection.schema.each do |field|
      if params[:item][field.to_s].blank? && !field.is_file
        @item[field.name]=nil
      elsif field.is_file
        #do nothing
        unless params[:item][field.to_s].nil?
          new_file = @file_collection.items.new()
          new_file.file =params[:item][field.to_s]
          new_file.save
          @item[field.name]='{"project":{"id": "'+@project.id+'"}, "collection":{"id": "'+@file_collection.id+'"},"item":{"id": "'+new_file.id.to_s+'", "display": "'+new_file.original_filename+'"}}'
        end
      else
        @item[field.name] = params[:item][field.to_s]
      end
    end
    if @item.save
      update_associated_fields(@item, @collection, @project)
      respond_to do |format|
        format.html do
          flash[:notice] = "Item Updated Successfully!"
        end
        #format.json { render json: @item.to_json, status: :updated}
        format.js { render :js => '$("#message").html("<h2>Item updated. Close window and refresh your page.</h2>").attr("class","message notice"); $("html, body").animate({scrollTop: "0px"})' }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = ["Item failed to save! Errors:", @item.errors.full_messages].flatten.join(' ')
        end
        format.json { render json: @item.to_json, status: :error}
        format.js { render :js => '$("#message").html("<h2>Item failed update.</h2>").attr("class","message error").scrollTop(0); $("html, body").animate({scrollTop: "0px"})' }
      end
    end
    redirect_to :back
  end
  
  def show
    @item = @collection.items.get(params[:id])
  end

  def edit
    @item = @collection.items.get(params[:id])
  end

  def new
  end
  
  def destroy
    @item = @collection.items.get(params[:id])
    if @item.destroy
      flash[:notice] = "Item was Deleted."
      redirect_to project_collection_path(@project, @collection)
    else
      flash[:error] = "Item failed to Delete"
      render :index
    end
  end
  
  def export
    @item = @collection.items.get(params[:id])
    filename ="#{@collection.name}.csv"
    send_data(@items.to_csv,
      :type => 'text/csv; charset=utf-8; header=present',
      :filename => filename)
  end
  
  def create
    @item = @collection.items.new(params[:item])
    @collection.schema.each do |field|
      if @item[field.name].blank?
        @item[field.name]=nil
      elsif field.is_file
        new_file = @file_collection.items.new()
        new_file.file =params[:item][field.to_s]
        new_file.save
        @item[field.name]='{"project":{"id": "'+@project.id+'"}, "collection":{"id": "'+@file_collection.id+'"},"item":{"id": "'+new_file.id.to_s+'", "display": "'+new_file.original_filename+'"}}'
      end
    end
    if @item.save
      flash[:notice] = "Item Saved!"
      redirect_to :back
      #redirect_to project_collection_items_path(@project, @collection)
    else
      flash[:error] = "Item failed to save: #{@item.errors.to_hash.map{|h| Yogo::Collection::Property.get(h.to_s.split(',')[0].gsub("[:field_",'').gsub('_','-')).name + h.to_s.split(',')[1].gsub(h.to_s.split(',')[0].gsub("field_",'Field ').gsub('_',' '),'')}.join(', ')}"
      
      #+ h.split(',')[1][0].gsub(h.to_s.split(',')[0].gsub("field_",'Field ').gsub('_',' '),'')
      redirect_to :back
      #render :back
    end
  end
  
  private

  def get_dependencies
    if !current_user.memberships(:project_id => params[:project_id]).empty? || Yogo::Project.get(params[:project_id]).private == false || Yogo::Collection::Data.get(params[:collection_id]).private == false
      @project = Yogo::Project.get(params[:project_id])
      @collection = @project.data_collections.get(params[:collection_id])
      @file_collection = @project.data_collections.first(:category=>"Files")
    else
      flash[:error] = "You don't have access to that project!"
      redirect_to projects_path()
      return
    end 
  end
  
  def update_project_stats
    @project.update_stats
  end
  
  def update_associated_fields(item, collection, project)
    collection.schema.all.each do |schema|
      associated_columns = Yogo::Project.all.data_collections.schemas.all(:associated_schema_id=>schema.id)
      associated_columns.each do |col|
        field_name = "field_"+col.id.to_s.gsub("-","_")
        col.data_collection.items.all(field_name.to_sym.like => '%{"project":{"id": "'+project.id+'"}, "collection":{"id": "'+collection.id+'"},"item":{"id": "'+item.id.to_s+'",%').each do |i|
          i[col.name] = '{"project":{"id": "'+project.id+'"}, "collection":{"id": "'+collection.id+'"},"item":{"id": "'+item.id.to_s+'", "display": "'+item[schema.name]+'"}}'
          i.save
        end
      end
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  
  def field_value_options(schema)
    schema.data_collection.items.map{|i| [i[schema.name],i[schema.name]] }
  end
  
  def associated_field_value_options(schema)
    schema.data_collection.items_json_array(schema.field_name, schema.data_collection.project_id, schema.data_collection.id)
  end
  
  def associated_field_display_options(schema)
    schema.data_collection.items_value_array(schema.field_name)
  end
  
  def associated_file_options(file_collection)
    file_collection.files_array(file_collection.project_id, file_collection.id)
  end
end

app/views/items/_form.haml
- collection.schema.each do |field|
  %label= field.name
  -if field.controlled_vocabulary
    = f.select(field.to_s, field_value_options(field.controlled_vocabulary), :include_blank => true)
  -elsif field.is_file == true
    -unless @item[field.name].nil?
      -json_string = JSON.parse(@item[field.name])
      %a.as-show(href='' data-toggle='modal' class='#{s.id.to_s}')= json_string['item']['display']
    =# f.select(field.to_s, associated_file_options(file_collection), :include_blank => true)
    = f.file_field(field.to_s, :class => 'input-medium')
  -elsif field.associated_schema
    = f.select(field.to_s, associated_field_value_options(field.associated_schema), :include_blank => true)
  -elsif field.type.to_s == "Yogo::Collection::Property::Date"
    = f.text_field(field.to_s, :id=> field.to_s) 
    :javascript
      $("##{field.to_s}").datepicker({dateFormat:'yy-mm-dd'});
  -elsif field.type.to_s == "Yogo::Collection::Property::DateTime"
    = f.text_field(field.to_s, :id=> field.to_s) 
    :javascript
      $("##{field.to_s}").datetimepicker({dateFormat:'yy-mm-dd'});
  -elsif field.type.to_s == "Yogo::Collection::Property::Text"
    = f.text_area(field.to_s, :id=> field.to_s, :placeholder => field.name, :class => 'input-large', :rows => 5) 
  -elsif field.type.to_s == "Yogo::Collection::Property::Boolean"
    %label 
      = f.check_box(field.to_s, :id=> field.to_s, :class => 'input-medium') 
      = field.name
  -else
    = f.text_field(field.to_s) 

app/views/items/_grid_new.haml
= javascript_include_tag 'slickgrid/jquery.event.drag-2.0.min.js','slickgrid/slick.core.js','slickgrid/slick.grid.js','slickgrid/slick.headerbuttons.js'
= stylesheet_link_tag 'slickgrid/jquery-ui-1.8.16.custom.css','slickgrid/slick.grid.css','slickgrid/grid_style.css','slickgrid/slick.headerbuttons.css'

#myGrid.span11{:style=>"height: 330px;"}

:javascript
  function load_modal(url){
    $("body").modalmanager("loading");setTimeout(function(){
      $("#ajax-modal").load(url, "", function(){
        $("#ajax-modal").modal();
      });
    }, 1000);
  }
  function load_widemodal(url){
    $("body").modalmanager("loading");setTimeout(function(){
      $("#ajax-modal-fw").load(url, "", function(){
        $("#ajax-modal-fw").modal();
      });
    }, 1000);
  }
  var data ="";
  
  function buttonFormatter(row, cell, value, columnDef, dataContext) {
    var base_url ="#{project_collection_path(project,collection)}/items/"+value.toString();
    
    var buttons =  '<a id="show_'+value.toString()+'" class="icon-time item-show" data-toggle="modal" href="#" onclick="load_widemodal(\''+base_url + '\')"></a><a id="edit_'+value.toString()+'" class="icon-edit item-edit" data-toggle="modal" href="#" onclick="load_modal(\''+base_url + '/edit\')"></a><a class="icon-remove-circle" href="'+base_url+'" data-method="delete" data-confirm="Are you sure you wish to delete this Item?" rel="nofollow"></a>';


    return buttons;
  }
  function editFormatter(row, cell, value, columnDef, dataContext) {
    return '<a class="icon-time item-edit" data-toggle="modal" href="#"></a>'

  }
  
  function historyFormatter(row, cell, value, columnDef, dataContext) {
    return '<a class="icon-time item-show" data-toggle="modal" href="#"></a>'
  }
  
  function cvFormatter(row, cell, value, columnDef, dataContext) {
    if (value != null)
      return value
    else
      return ""
    end
  }
  
  function assocFormatter(row, cell, value, columnDef, dataContext) {
    if (value != null)
    {  
      json_string = JSON.parse(value)
      
      var url ="/projects/"+json_string['project']['id']+"/collections/"+json_string['collection']['id']+"/items/"+json_string['item']['id'];
      var val = '<a id="show_'+value.toString()+'" class="icon-edit item-show" data-toggle="modal" href="#" onclick="load_modal(\''+url + '/edit\')"></a><a id="show_'+value.toString()+'" class="item-show" data-toggle="modal" href="#" onclick="load_widemodal(\''+url +'\')">' + json_string['item']['display']+'</a>';
      return val;

    }
    else
      return ""
    end

  }
  
  function fileFormatter(row, cell, value, columnDef, dataContext) {
    if (value != null)
      return '<a href="#{root_url}asset_collection/#{collection.id.to_s}/' + value + '">Download</a>'
    else
      return ""
    end
  }

  
  
  function showDialog(url){
     $("#term_info").html('<iframe id="modalIframeId" width="100%" height="100%" marginWidth="0" marginHeight="0" frameBorder="0" scrolling="auto"/>').dialog("open");
     $("#modalIframeId").attr("src",url);
     return false;
  }

  $(document).ready(function() {
     $("#term_info").dialog({
             autoOpen: false,
             modal: true,
             height: 500,
             width: 950
         });
        // grid = new Slick.Grid("#myGrid", data, columns, options);

         
         
         
         var grid;

         var columns =[ {id: "button", name: "", field: "id", formatter: buttonFormatter, minWidth: 80, },#{collection.schema.map{|s| '{id: "'+ s.field_name + '", name: "' + s.name + '", field: "' + s.field_name + '", minWidth: 150, header: {buttons: [{cssClass: "icon-edit",tooltip: "Edit Column.",handler: function(e){load_modal(\''+edit_project_collection_schema_path(project,collection,s)+'\')}}]},sortable: true' + "#{s.controlled_vocabulary_id.nil? ? "" : ", formatter: cvFormatter"}" + "#{s.associated_schema_id.nil? ? "" : ", formatter: assocFormatter"}" + "#{s.is_file ?  ", formatter: assocFormatter" : ""}" + '}'}.join(',')}];

         var options = {
           enableCellNavigation: true,
           enableColumnReorder: false,
           multiColumnSort: true,
           enableRowReordering: true
           //forceFitColumns: true
         };

        
         columns[0].header = {
             buttons: [
               {
                 cssClass: "icon-plus btn btn-mini schema-new",
                 tooltip: "Add Column",
                 handler: function(e) {
                   load_modal('#{new_project_collection_schema_path(project,collection)}')
                 }
               },
               {
                  cssClass: "btn btn-mini icon-filter",
                  tooltip: "Filter",
                  handler: function(e) {
                    $('#edit-filters').modal();
                  }
                },
             ]
           };
           
        data= #{items_raw.to_json}
        // $(function () {


           grid = new Slick.Grid("#myGrid", data, columns, options);
           
           var headerButtonsPlugin = new Slick.Plugins.HeaderButtons();

           grid.registerPlugin(headerButtonsPlugin);
           
           grid.onSort.subscribe(function (e, args) {
             var cols = args.sortCols;
           
             data.sort(function (dataRow1, dataRow2) {
               for (var i = 0, l = cols.length; i < l; i++) {
                 var field = cols[i].sortCol.field;
                 var sign = cols[i].sortAsc ? 1 : -1;
                 var value1 = dataRow1[field], value2 = dataRow2[field];
                 var result = (value1 == value2 ? 0 : (value1 > value2 ? 1 : -1)) * sign;
                 if (result != 0) {
                   return result;
                 }
               }
               return 0;
             });
              grid.invalidate();
              grid.render();
              grid.autosizeColumns();
           });
         //})
  });
  
%br(clear = 'all')

app/views/items/_inline_form.haml
%strong Quick Add
= form_for("item", @item, :url => project_collection_items_path(@project, collection), :html => {"multipart" => true, "data-ajax"=> false, :class => 'form-inline', :id => 'QAcreateItemForm', 'data-focus-on' => "input:visible:first"}) do |f| 
  - collection.schema.each do |field|
    -if field.controlled_vocabulary
      = f.select(field.to_s, field_value_options(field.controlled_vocabulary), 
                {:include_blank => field.name}, {:class => 'input-medium'})
    -elsif field.is_file == true
      %label 
        = field.name
      = f.file_field(field.to_s, :class => 'input-medium')
    -elsif field.associated_schema
      = f.select(field.to_s, associated_field_value_options(field.associated_schema), 
                {:include_blank => field.name}, {:class => 'input-medium'})
    -elsif field.type.to_s == "Yogo::Collection::Property::Date"
      = f.text_field(field.to_s, :id=> "c_"+field.to_s, :placeholder => field.name, :class => 'input-medium') 
      :javascript
        $("#c_#{field.to_s}").datepicker({dateFormat:'yy-mm-dd'});
    -elsif field.type.to_s == "Yogo::Collection::Property::DateTime"
      = f.text_field(field.to_s, :id=> "c_"+field.to_s, :placeholder => field.name, :class => 'input-medium') 
      :javascript
        $("#c_#{field.to_s}").datetimepicker({dateFormat:'yy-mm-dd'});
    -elsif field.type.to_s == "Yogo::Collection::Property::Text"
      = f.text_field(field.to_s, :id=> field.to_s, :placeholder => field.name, :class => 'input-large', :rows => 4) 
    -elsif field.type.to_s == "Yogo::Collection::Property::Boolean"
      %label 
        = f.check_box(field.to_s, :id=> field.to_s, :class => 'input-medium') 
        = field.name
    
    -else
      = f.text_field(field.to_s, :placeholder => field.name, :class => 'input-medium') 
  -#= f.file_field(:file, :class => 'input-medium')
  %button.btn-small.btn-primary Save

:javascript
  function formfocus() {
    $('#QAcreateItemForm input:visible:first').focus();
  }
  window.onload = formfocus;

app/views/items/_public_table.haml
:javascript
  $(document).ready(function() {
    $('.data-table').dataTable();
  } );
-@schema_cv_hash={}
-collection.schema.each do |s|
  -link_hash={}
  -if s.controlled_vocabulary_id
  -@schema_cv_hash[s.id] =Yogo::Collection::Property.get(s.controlled_vocabulary_id).data_collection
    -s.data_collection.items.each do |i|
      -link_hash = link_hash.merge({i[s.name] => @schema_cv_hash[s.id].items.first("field_#{s.controlled_vocabulary_id.to_s.gsub('-','_')}".to_sym=>i[s.name])})
    -@schema_cv_hash[s.name]=link_hash
    
%table.data-table.table.table-condensed.table-striped
  %thead
    %tr
      %th.action-column
        %a.btn.btn-mini(href='#edit-filters' data-toggle='modal' title='Filter Data Grid') 
          %i.icon-filter
      - collection.schema.each do |s|
        %th.column
          %a.icon-info-sign(href='#' data-toggle='modal' class='#{s.id.to_s}')
          = s.name
          :javascript
            //Schemas#show (Edit Column Icon Link)
            #{ajax_modal_js("th a.#{s.id.to_s}", project_collection_schema_path(@project,@collection,s))}

      %th File
  %tbody
    - items.each do |i|
      %tr(class='#{i.id.to_s}')
        %td
          %a.icon-time.item-show(href='#' data-toggle='modal')
          :javascript
            //Items#show (Data Row History Icon Link)
            #{ajax_modal_js(".#{i.id.to_s} a.item-show", project_collection_item_path(project,collection,i), true)}
        - collection.schema.each do |s|
          -if s.controlled_vocabulary_id  
            -if @schema_cv_hash[s.name][i[s.name]]
              %td
                - if i[s.name]
                  %a.item-cv(href='#' data-toggle='modal' class='#{s.id.to_s}')= i[s.name]
                  :javascript
                    //Items#Show (Controlled Vocabulary Link)
                    #{ajax_modal_js(".#{i.id.to_s} a.item-cv.#{s.id.to_s}", project_collection_item_path(@schema_cv_hash[s.id].project_id,@schema_cv_hash[s.id],@schema_cv_hash[s.name][i[s.name]]), true)}
            -else
              %td.danger= i[s.name]
          -elsif s.associated_schema     
            %td
              - if i[s.name]
                -json_string = JSON.parse(i[s.name])
                %a.as-show(href='' data-toggle='modal' class='#{s.id.to_s}')= json_string['item']['display']
                :javascript
                  //Items#show (Association Item Show Link)
                  #{ajax_modal_js(".#{i.id.to_s} a.as-show.#{s.id.to_s}", project_collection_item_path(json_string['project']['id'],json_string['collection']['id'],json_string['item']['id']), true)}
          -else
            %td
              - if i[s.name].to_s.length > 42
                = i[s.name][0..42]
                %a.btn-info.btn-mini(href='#' data-placement='right' data-content="#{i[s.name].gsub('"', '\"')}" rel='popover' data-original-title='#{s.name}')
                  = '...'
              - else
                = i[s.name]
        %td
          %a{:href => i.file.to_s}= i.original_filename

app/views/items/_table.haml
-# TODO:
-# Dear god fix the awful javascript on this page. Sooo much technical debt... -pol
-#

:javascript
  $(document).ready(function() {
    $('.data-table').dataTable();
  } );
-@schema_cv_hash={}
-collection.schema.each do |s|
  -link_hash={}
  -if s.controlled_vocabulary_id
  -@schema_cv_hash[s.id] =Yogo::Collection::Property.get(s.controlled_vocabulary_id).data_collection
    -s.data_collection.items.each do |i|
      -link_hash = link_hash.merge({i[s.name] => @schema_cv_hash[s.id].items.first("field_#{s.controlled_vocabulary_id.to_s.gsub('-','_')}".to_sym=>i[s.name])})
    -@schema_cv_hash[s.name]=link_hash

%table.data-table.table.table-condensed.table-striped
  %thead
    %tr
      %th.action-column
        -unless collection.category == "Files"
          %a.btn.btn-mini.schema-new(href='#' data-toggle='modal' title='Add Column') 
            %i.icon-plus
        %a.btn.btn-mini(href='#edit-filters' data-toggle='modal' title='Filter Data Grid') 
          %i.icon-filter
      - collection.schema.each do |s|
        %th.column
          %a.icon-edit(href='' data-toggle='modal' class='#{s.id.to_s}')
          = s.name
          :javascript
            //Schemas#edit (Edit Column Icon Link)
            #{ajax_modal_js("th a.#{s.id.to_s}", edit_project_collection_schema_path(project,collection,s))}
      -if collection.category == "Files"
        %th File
  %tbody
    - items.each do |i|
      %tr(class='#{i.id.to_s}')
        %td
          %a.icon-time.item-show(href='#' data-toggle='modal')
          %a.icon-edit.item-edit(href='#' data-toggle='modal')
          = link_to("", project_collection_item_path(project,collection,i), :class => 'icon-remove-circle',:method=>:delete, 
                    "data-confirm"=>"Are you sure you wish to delete this Data Row?")
          :javascript
            //Items#show (Data Row History Icon Link)
            #{ajax_modal_js(".#{i.id.to_s} a.item-show", project_collection_item_path(project,collection,i), true)}
            //Items#edit (Data Row Edit Icon Link)
            #{ajax_modal_js(".#{i.id.to_s} a.item-edit", edit_project_collection_item_path(project,collection,i))}

        - collection.schema.each do |s|
          -if s.controlled_vocabulary_id  
            -if @schema_cv_hash[s.name][i[s.name]]
              %td
                - if i[s.name] # if it is nil, don't do it
                  %a.item-cv(href='#' data-toggle='modal' class='#{s.id.to_s}')= i[s.name]
                  :javascript
                    //Items#Show (Controlled Vocabulary Link)
                    #{ajax_modal_js(".#{i.id.to_s} a.item-cv.#{s.id.to_s}", project_collection_item_path(@schema_cv_hash[s.id].project_id,@schema_cv_hash[s.id],@schema_cv_hash[s.name][i[s.name]]), true)}
            -else
              %td.danger= i[s.name]
          -elsif s.associated_schema || s.is_file   
            %td
              - unless i[s.name].nil? # if it is nil, don't do it.
                -json_string = JSON.parse(i[s.name])

                %a.as-show(href='' data-toggle='modal' class='#{s.id.to_s}')= json_string['item']['display']
                :javascript
                  //Items#show (Association Item Show Link)
                  #{ajax_modal_js(".#{i.id.to_s} a.as-show.#{s.id.to_s}", project_collection_item_path(json_string['project']['id'],json_string['collection']['id'],json_string['item']['id']), true)}
                  //Items#edit (Association Item Edit Icon Link)
                  #{ajax_modal_js(".#{i.id.to_s} a.as-edit.#{s.id.to_s}", edit_project_collection_item_path(json_string['project']['id'],json_string['collection']['id'],json_string['item']['id']))}
          -else
            %td
              - if i[s.name].to_s.length > 42
                = i[s.name][0..42]
                %a.btn-info.btn-mini(href='#' data-placement='right' data-content="#{i[s.name].gsub('"', '\"')}" rel='popover' data-original-title='#{s.name}')
                  = '...'
              - else
                = i[s.name]
        -if collection.category == "Files"
          %td
            %a{:href => i.file.to_s}= i.original_filename

app/views/items/_version_table.haml
-@schema_cv_hash={}
-collection.schema.each do |s|
  -link_hash={}
  -if s.controlled_vocabulary_id
  -@schema_cv_hash[s.id] =Yogo::Collection::Property.get(s.controlled_vocabulary_id).data_collection
    -s.data_collection.items.each do |i|
      -link_hash = link_hash.merge({i[s.name] => @schema_cv_hash[s.id].items.first("field_#{s.controlled_vocabulary_id.to_s.gsub('-','_')}".to_sym=>i[s.name])})
    -@schema_cv_hash[s.name]=link_hash

-# CV Modal
#cv-modal.modal.hide.fade
  .modal-header
    %button.close(data-dismiss="modal") x
    %h3 CV Term Metadata
    .modal-body
    .modal-footer

-# Assoc Modal
#assoc-modal.modal.hide.fade
  .modal-header
    %button.close(data-dismiss="modal") x
    %h3 Associated Data
    .modal-body
    .modal-footer

%table.table.table-condensed.table-striped
  %thead
    %tr
      %th Restore
      %th Version Date
      %th Changelog
      - collection.schema.each do |s|
        %th= s.name
      - if collection == @file_collection
        %th File
  %tbody
    %tr
      %td &nbsp;
      %td= item.updated_at.strftime("%B %d, %Y %I:%M:%S %p")
      %td Current Version
      - collection.schema.each do |s|
        -if s.controlled_vocabulary_id  
          -if @schema_cv_hash[s.name][item[s.name]]
            %td
              %a(href='#{project_collection_item_path(@schema_cv_hash[s.id].project_id,@schema_cv_hash[s.id],@schema_cv_hash[s.name][item[s.name]])}' data-toggle='modal' data-target='#cv-modal')= item[s.name]
          -else
            %td.danger= item[s.name]
        -elsif s.associated_schema     
          %td
            - unless item[s.name].nil?
              -json_string = JSON.parse(item[s.name])
              %a(href='#{project_collection_item_path(json_string['project']['id'],json_string['collection']['id'],json_string['item']['id'])}' data-toggle='modal' data-target='#assoc-modal')= json_string['item']['display']
        -else
          %td= item[s.name]
      -if collection == @file_collection
        %td
          %a{:href => item.file.to_s}= item.original_filename

    - item.versions.reverse.each do |i|
      %tr
        %td
          = link_to("<i class='icon-upload-alt'></i>".html_safe, 
            project_collection_item_restore_path(project,collection,item, :deleted_at=>i.deleted_at), 
              :class => 'btn btn-mini', :method=>:put, 
              "data-confirm"=>"Are you sure you wish to restore this version?")
        %td= i.updated_at.strftime("%B %d, %Y %I:%M:%S %p")
        %td= collection.schema.inject(i.updated_comment) { |c, s| c.gsub(s.to_s, s.name) }
        - collection.schema.each do |s|
          -if s.controlled_vocabulary_id  
            -if @schema_cv_hash[s.name][i[s.name]]
              %td
                %a(href='#{project_collection_item_path(@schema_cv_hash[s.id].project_id,@schema_cv_hash[s.id],@schema_cv_hash[s.name][i[s.name]])}' data-toggle='modal' data-target='#cv-modal')= i[s.name]
            -else
              %td.danger= i[s.name]
          -elsif s.associated_schema     
            %td
              - unless i[s.name].nil?
                -json_string = JSON.parse(i[s.name])
                %a(href='#{project_collection_item_path(json_string['project']['id'],json_string['collection']['id'],json_string['item']['id'])}' data-toggle='modal' data-target='#assoc-modal')= json_string['item']['display']
          -else
            %td= i[s.name]
        -#%td
        -#%a{:href => i.file.to_s}= i.original_filename

app/views/items/edit.haml
.content-box
  .modal-header
    %h3 Edit #{@collection.name} Data Row
    %p.muted Data Row ID: #{@item.id}
  = form_for("item", @item, :url => project_collection_item_path(@project, @collection, @item), 
            :html=>{"multipart" => true, :method=>"put", :class => 'form-box', :ajax=>false}) do |f| 
    .modal-body
      = render :partial => 'items/form', :locals => {:f => f, :collection => @collection, :file_collection => @file_collection}
    .modal-footer
      %button.btn.btn-primary Save Changes
      %a.btn(data-dismiss="modal") Close

app/views/items/index.haml
.content-box
  - if @collection.schema.count > 0
    -if current_user.member_of?(@project)
      = render  :partial => 'items/table', 
                :locals => {:items =>@items, :collection => @collection, :project=>@project}
    -else
      = render  :partial => 'items/public_table', 
                :locals => {:items => @items, :collection => @collection, :project=>@project}

app/views/items/new.haml
= form_for("item", :url => project_collection_items_path(@project, @collection), :html => {"multipart" => true, "data-ajax"=> false, :class => 'form-box'}) do |f| 
  = render :partial => 'items/form', :locals => {:f => f, :collection => @collection}
  .modal-footer
    %button.btn.btn-primary Save Changes
    %a.btn(data-dismiss="modal") Close

app/views/items/show.haml
.content-box
  .modal-header
    %h3 #{@collection.name} Data Row
    %p.muted Data Row ID:#{@item.id}
  .modal-body
    = render :partial => 'items/version_table', :locals => {:item => @item, :collection => @collection, :item => @item, :project=> @project}
  .modal-footer
    %a.btn(data-dismiss="modal") Close