config/routes.rb
Sapphire::Application.routes.draw do

  devise_for :users

  resources :projects do 
    get :search
    get :s, :action => :search_results
    get :upload
    post :upload, :action => :process_upload
    get :add_user
    put :remove_user
    post :associate_user
    post :publish
    resources :collections do
      get :upload
      post :publish
      post :upload, :controller => :projects, :action => :process_upload
      get :export
      get :export_with_files
      get :cv
      get :edit_cv
      resources :items do
        put :restore
      end
      resources :schemas do
        put :restore
      end
    end
  end

  root :to => 'projects#index'

end

app/views/layouts/_ajax_modals.haml
/ Le Javascript Ajax Modals
:javascript
  //Projects#new (New Project)
  #{ajax_modal_js("#header li.project-new a", new_project_path)}
  //Projects#new (New Project Prompt Button)
  #{ajax_modal_js("a.btn.project-new", new_project_path)}
- if @project
  :javascript
    //Projects#edit (Project Settings)
    #{ajax_modal_js("#header li.project-edit a", edit_project_path(@project))}
    //Collections#new (New Collection)
    #{ajax_modal_js("#header li.collection-new a", new_project_collection_path(@project))}
    //Collections#new (New Collection Prompt Button)
    #{ajax_modal_js("a.btn.collection-new", new_project_collection_path(@project))}
- if @collection
  :javascript
    //Collections#edt (Collection Settings)
    #{ajax_modal_js("#header li.collection-edit a", edit_project_collection_path(@project, @collection))}
    //Schemas#new (Add Column)
    #{ajax_modal_js("#header li.schema-new a", new_project_collection_schema_path(@project,@collection))}
    //Schemas#new (Add Column Table Link Button) (Add Column New Collection Prompt Button)
    #{ajax_modal_js("a.schema-new", new_project_collection_schema_path(@project,@collection))}

app/views/layouts/_alerts.haml
-# There are four alert styles: default, alert-success, alert-info, alert-error
-# Default is a yellow allert message (you don't need to add an alert-type class)
-# alert-success: green
-# alert-info: blue
-# alert-error: red
-# see here for more info: http://twitter.github.com/bootstrap/javascript.html#alerts
- flash.each do |type, message|
  .alert.fade.in{:class => alert_type(type) }
    %button.close(type="button" data-dismiss="alert") &times;
    %strong= message

:javascript
  $('.alert.alert-info').delay(3 * 1000).fadeOut();
  // Note: keep the errors on the screen to be cleared manually!

app/views/layouts/_breadcrumbs.haml
%ul.breadcrumb
  - if @project
    %li
      Project: 
      = link_to @project.name, project_path(@project)
      - if @collection
        %span.divider /

    - if @collection
      %li
        Collection: 
        = link_to @collection.name, project_collection_path(@project, @collection)

app/views/layouts/_footer.haml
%hr
%footer
  %p.muted
    Copyright &copy; #{Time.now.year} Montana State University

app/views/layouts/_header.haml
#header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to(image_tag('Yogo-50x40px-wh.png') + ' Sapphire', root_path, :class => 'brand')
      %ul.nav
        - if current_user
          %li.dropdown
            %a.dropdown-toggle(href='#' data-toggle='dropdown') 
              Project
              %b.caret
            %ul.dropdown-menu(role='menu')
              %li.dropdown-submenu
                %a(href="#" data-toggle='dropdown') Projects
                %ul.dropdown-menu
                  %li= link_to 'All Projects', root_path
                  %li.divider
                  - current_user.memberships.projects.each do |p|
                    - next if p.new?
                    %li= link_to p.name, project_path(p)
              %li.project-new= link_to('New Project', '#', 'data-toggle' => 'modal')
        - if @project
          %li.divider-vertical

        - if @project 
          %li.dropdown
            %a.dropdown-toggle(href='#' data-toggle='dropdown') 
              = @project.name
              %b.caret
            %ul.dropdown-menu(role='menu')
              %li= link_to @project.name, project_path(@project)
              %li.dropdown-submenu 
                %a(href='#' data-toggle='dropdown') Data Collections
                %ul.dropdown-menu
                  %li= link_to 'All Data Collections', project_path(@project)
                  %li.divider
                  - @project.collections.each do |c|
                    - next if c.new?
                    %li= link_to c.name, project_collection_path(@project, c)
              %li.divider
              -if @project && current_user.member_of?(@project)
                %li.project-edit= link_to('Project Settings', '#', 'data-toggle' => 'modal')
                %li= link_to('Project Members',     '#project_users',       'data-toggle' => 'modal')
                %li.collection-new= link_to('New Collection', '#', 'data-toggle' => 'modal')
                %li= link_to('Upload Project Data', '#upload_form',         'data-toggle' => 'modal')
                -#%li
                -#  -if @project && @project.private?
                -#    = link_to('Publish Project',   project_publish_path(@project), :method => 'post')
                -#  -else
                -#    = link_to('Unpublish Project', project_publish_path(@project), :method => 'post')
        - if @collection
          %li.divider-vertical 

          - if @collection && @collection.category != "Files"
            %li.dropdown
              %a.dropdown-toggle(href='#' data-toggle='dropdown') 
                = @collection.name
                %b.caret
              %ul.dropdown-menu(role='menu')
                %li= link_to @collection.name, project_collection_path(@project, @collection)
                %li.divider
                -if @project && current_user.member_of?(@project)
                  %li.collection-edit= link_to('Collection Settings','#','data-toggle' => 'modal')
                  %li.schema-new= link_to('Add Column', '#', 'data-toggle' => 'modal')
                  %li= link_to('Upload Collection Data', '#upload_form',            'data-toggle' => 'modal')
                  %li= link_to('Filter',                 '#edit-filters',           'data-toggle' => 'modal')
                  - if @filters && !@filters.empty?
                    %li=link_to('Clear Filter', project_collection_path(@project, @collection))
                  -if @collection && @collection.saved?
                    %li= link_to('Download Metadata', 
                            project_collection_export_path( @project, @collection, :filters => params[:filters]))
                    %li= link_to('Download All Data', 
                            project_collection_export_with_files_path( @project, @collection, :filters => params[:filters]))
      %ul.nav.pull-right
        - if @project && !@project.new?
          %li= link_to('Search', '#project_search_form', 'data-toggle' => 'modal')
        - if current_user
          %li= link_to 'Profile', edit_user_registration_path
          %li= link_to("Logout (#{current_user.first_name})", destroy_user_session_path, :method=> :delete)

app/views/layouts/_nav_modals.haml
-# Todo: make modals stack by generating ajax modal divs into the DOM prior to ajax load
-# Standard width modal
#ajax-modal.modal.hide.fade(data-focus-on="input:visible:first")

-# Full width modal
#ajax-modal-fw.container.modal.hide.fade(data-focus-on="input:visible:first")

- if @project
  -# Projects#search form
  #project_search_form.modal.hide.fade
    .modal-header
      %button.close(data-dismiss="modal") x
      %h3 Search Data in #{@project.name}
    = form_for(:search, :url => project_s_path(@project), :html => {:class => 'form', :method => :get}) do |f|
      .modal-body
        %label Search Terms
        = f.text_field(:terms, :class => 'span5')
      .modal-footer
        %button.btn.btn-primary Search
        %a.btn.btn-mini(data-dismiss="modal") Close

  -# Project#upload_data form
  #upload_form.modal.hide.fade
    .modal-header
      %button.close(data-dismiss="modal") x
      %h3 Upload Data
    = render :partial => 'projects/upload_form'
    
  -# Project#project_users form
  #project_users.modal.hide.fade
    .modal-header
      %button.close(data-dismiss="modal") x
      %h3 Project Users
    = render :partial => 'projects/project_users'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    / Always force latest IE rendering engine (even in intranet) &amp; Chrome Frame
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}/
    %title Yogo 
    = stylesheet_link_tag 'datatable',
    'jquery-ui',
    'font-awesome',
    'bootstrap',
    'bootstrap-responsive',
    'bootstrap-modal',
    'application'
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = javascript_include_tag 'jquery',
      'jquery-ui',
      'jquery-ui-timepicker-addon',
      'jquery-dataTables',
      'jquery_ujs',
      'bootstrap',
      'bootstrap-modalmanager',
      'bootstrap-modal',
      :cache => false
    = csrf_meta_tag
  %body
    .container
      = render :partial => 'layouts/header'
      = render :partial => 'layouts/nav_modals'
      = render :partial => 'layouts/breadcrumbs'
      = render :partial => 'layouts/alerts'
      = yield
      = render :partial => 'layouts/footer'
      = render :partial => 'layouts/ajax_modals'

app/views/layouts/blank.haml
!!!
%html
  %head
    %title Yogo Sapphire
    = stylesheet_link_tag 'datatable',
    'jquery-ui',
    'font-awesome',
    'bootstrap',
    'bootstrap-responsive',
    'bootstrap-modal',
    'application'
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = javascript_include_tag 'jquery',
      'jquery_ujs',
      'bootstrap',
      'bootstrap-modal',
      'bootstrap-modalmanager',
      'jquery-ui',
      'jquery-ui-timepicker-addon',
      'jquery-dataTables',
      :cache => false
    = csrf_meta_tag
  %body
    = yield